### ISSUE TITLE
Project cannot be opened

### ISSUE THREAD

**Issue by NYamaguchi415** [matafc/hachimaru-blog#1]
Hey Hachimaru,

I just completed my first iOS app using kivy and have been having a ton of issues trying to add in an ad network. I saw this and would definitely like to learn how to incorporate this into my app. 

downloaded the files and followed your instructions, but when i try to open the xcodeproj file i'm running into an error saying

"Project /app-kivy-iad-sample/kivy-iad-sample.xcodeproj cannot be opened because the project file cannot be pars"

Could you help me out?

**Comment by matafc** [comment]
The command 

``` bash
bash scripts/setup_xcode.sh
```

is not working because the kivy-ios repo updated and there is a merge conflict. I will update the script to get it working and have you try again.

**Comment by matafc** [comment]
I added some more instructions in the readme and changed setup_xcode.sh. It is now working on my computer. Try again and let me know if it resolved your issue or not.

**Comment by NYamaguchi415** [comment]
Awesome, it worked perfectly. Thanks so much Frank!
